"""empty message

Revision ID: ad740d479195
Revises: 89ec2012273e
Create Date: 2021-05-08 18:17:07.138481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad740d479195'
down_revision = '89ec2012273e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping', 'Edited_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping', sa.Column('Edited_by', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
